package main

// **********************************
Generated by ModelsGenerator
2020-04-22T20:32:23+03:00
// **********************************

type stupidenum int

const (
	stupidenumvalue = stupidenum(5)
	stupidenumanother = stupidenum(8)
)